# Generated by Django 3.2.9 on 2021-12-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name ')),
                ('email', models.EmailField(max_length=128, verbose_name='Email ')),
                ('subject', models.CharField(max_length=128, verbose_name='Subject ')),
                ('message', models.TextField(max_length=2800, verbose_name='Message ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date ')),
            ],
        ),
    ]
